#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	local enabled=$(uci -q get wifi-monitor.config.enabled || echo "0")
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance "main"
	procd_set_param command /usr/bin/wifi-monitor.sh
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "wifi-monitor"
}
